# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-01 22:55
from __future__ import unicode_literals

import TAHiring.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=6)),
            ],
            options={
                'verbose_name': 'Course',
            },
        ),
        migrations.CreateModel(
            name='Course_Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorials', to='TAHiring.Course')),
            ],
            options={
                'verbose_name': 'Tutorial',
            },
        ),
        migrations.CreateModel(
            name='TAAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_new', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'TA Availability',
                'verbose_name_plural': 'TA Availabilities',
            },
        ),
        migrations.CreateModel(
            name='TACourseInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TAHiring.Course')),
            ],
        ),
        migrations.CreateModel(
            name='TAData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('utorid', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15, validators=[TAHiring.models.TAData.phone_validator])),
                ('education', models.CharField(choices=[('UG2', 'Second Year Undegraduate'), ('UG3', 'Third Year Undegraduate'), ('UG4', 'Fourth Year Undegraduate'), ('MAS', 'Masters'), ('PHD', 'PhD')], max_length=3)),
                ('prev_courses', models.TextField(blank=True)),
                ('other_exp', models.TextField(blank=True)),
                ('num_tut_int', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('multi_class', models.BooleanField(default=True)),
                ('summer_ta', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'TA Information',
                'verbose_name_plural': 'TA Information',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('time_of_day', models.CharField(max_length=4, validators=[TAHiring.models.TimeSlot.time_validator])),
            ],
        ),
        migrations.AddField(
            model_name='tacourseinterest',
            name='ta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TAHiring.TAData'),
        ),
        migrations.AddField(
            model_name='taavailability',
            name='ta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='TAHiring.TAData'),
        ),
        migrations.AddField(
            model_name='taavailability',
            name='timeslot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ta_availability', to='TAHiring.TimeSlot'),
        ),
        migrations.AddField(
            model_name='course_tutorial',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorials', to='TAHiring.TimeSlot'),
        ),
    ]
