# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-09 16:17
from __future__ import unicode_literals

import TAHiring.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=6)),
                ('term', models.CharField(choices=[('F', 'Fall'), ('S', 'Spring'), ('Y', 'Full Year'), ('U', 'Summer')], default='F', max_length=1)),
            ],
            options={
                'verbose_name': 'Course',
            },
        ),
        migrations.CreateModel(
            name='CourseTutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4)),
                ('is_first', models.BooleanField(default=False)),
                ('is_last', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorials', to='TAHiring.Course')),
            ],
            options={
                'ordering': ['timeslot'],
                'verbose_name': 'Tutorial',
            },
        ),
        migrations.CreateModel(
            name='TAAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_new', models.BooleanField(default=False)),
                ('term', models.CharField(choices=[('F', 'Fall'), ('S', 'Spring'), ('Y', 'Full Year'), ('U', 'Summer')], default='F', max_length=1)),
            ],
            options={
                'ordering': ['ta', 'timeslot'],
                'verbose_name_plural': 'TA Availabilities',
                'verbose_name': 'TA Availability',
            },
        ),
        migrations.CreateModel(
            name='TACourseInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_new', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tas_interested', to='TAHiring.Course')),
            ],
        ),
        migrations.CreateModel(
            name='TAData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Last Name')),
                ('utorid', models.CharField(max_length=10, verbose_name='UTORid')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15, validators=[TAHiring.models.TAData.phone_validator])),
                ('education', models.CharField(choices=[('UG2', 'Second Year Undegraduate'), ('UG3', 'Third Year Undegraduate'), ('UG4', 'Fourth Year Undegraduate'), ('MAS', 'Masters'), ('PHD', 'PhD'), ('PD', 'Post-Doc'), ('ND', 'Non degree')], max_length=3, verbose_name='Education')),
                ('prev_courses', models.TextField(blank=True, verbose_name="Previous Courses TA'ed")),
                ('other_exp', models.TextField(blank=True, verbose_name='Other Experience')),
                ('num_tut_int', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Number of Tutorials')),
                ('multi_class', models.BooleanField(default=True, verbose_name='TA Multiple Classes')),
                ('summer_ta', models.BooleanField(default=True, verbose_name='Summer TAing')),
            ],
            options={
                'verbose_name_plural': 'TA Information',
                'verbose_name': 'TA Information',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('time_of_day', models.CharField(max_length=4, validators=[TAHiring.models.TimeSlot.time_validator])),
            ],
            options={
                'ordering': ['day_of_week', 'time_of_day'],
            },
        ),
        migrations.AddField(
            model_name='tacourseinterest',
            name='ta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_interested', to='TAHiring.TAData'),
        ),
        migrations.AddField(
            model_name='taavailability',
            name='ta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='TAHiring.TAData'),
        ),
        migrations.AddField(
            model_name='taavailability',
            name='timeslot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ta_availability', to='TAHiring.TimeSlot'),
        ),
        migrations.AddField(
            model_name='coursetutorial',
            name='ta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutorials', to='TAHiring.TAData'),
        ),
        migrations.AddField(
            model_name='coursetutorial',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorials', to='TAHiring.TimeSlot'),
        ),
    ]
