# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-02 17:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TAHiring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_tutorial',
            name='ta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutorials', to='TAHiring.TAData'),
        ),
        migrations.AlterField(
            model_name='tadata',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='tadata',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='tadata',
            name='multi_class',
            field=models.BooleanField(default=True, verbose_name='TA Multiple Classes'),
        ),
        migrations.AlterField(
            model_name='tadata',
            name='num_tut_int',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Number of Tutorials'),
        ),
        migrations.AlterField(
            model_name='tadata',
            name='other_exp',
            field=models.TextField(blank=True, verbose_name='Other Experience'),
        ),
        migrations.AlterField(
            model_name='tadata',
            name='prev_courses',
            field=models.TextField(blank=True, verbose_name="Previous Courses TA'ed"),
        ),
        migrations.AlterField(
            model_name='tadata',
            name='summer_ta',
            field=models.BooleanField(default=True, verbose_name='Summer TAing'),
        ),
        migrations.AlterField(
            model_name='tadata',
            name='utorid',
            field=models.CharField(max_length=10, verbose_name='UTORid'),
        ),
    ]
