# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-02 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TAHiring', '0002_auto_20170502_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tacourseinterest',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tas_interested', to='TAHiring.Course'),
        ),
        migrations.AlterField(
            model_name='tacourseinterest',
            name='ta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_interested', to='TAHiring.TAData'),
        ),
    ]
