# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-04 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TAHiring', '0004_tacourseinterest_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_tutorial',
            name='ta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutorials', to='TAHiring.TAData'),
        ),
        migrations.AlterField(
            model_name='tadata',
            name='education',
            field=models.CharField(choices=[('UG2', 'Second Year Undegraduate'), ('UG3', 'Third Year Undegraduate'), ('UG4', 'Fourth Year Undegraduate'), ('MAS', 'Masters'), ('PHD', 'PhD')], max_length=3, verbose_name='Education'),
        ),
    ]
