# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-04 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TAHiring', '0005_auto_20170504_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_tutorial',
            name='is_first',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course_tutorial',
            name='is_last',
            field=models.BooleanField(default=False),
        ),
    ]
